package rocks.ashleigh.lovejoy.datastructures;

import java.util.ArrayList;
import org.apache.commons.validator.routines.EmailValidator;

public class RegistrationForm {
    private String emailAddress;
    private String name;
    private String password;
    private String passwordConfirmation;
    private String phoneNumber;

    private boolean valid = false;
    private ArrayList<String> errors = new ArrayList<>();



    public boolean isValid() {
        return valid;
    }

    public ArrayList<String> getErrors() {
        return errors;
    }

    public boolean computeValidity() {

        errors.clear();

        // Check the email first
        if (!EmailValidator.getInstance().isValid(emailAddress)) {
            errors.add("Email address is invalid!");
        }



        // TODO: Confirm that user input is valid


        valid = errors.size() == 0;
        return isValid();
    }

    /** Getters and setters automatically generated by IntelliJ **/
    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPasswordConfirmation() {
        return passwordConfirmation;
    }

    public void setPasswordConfirmation(String passwordConfirmation) {
        this.passwordConfirmation = passwordConfirmation;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
